const discord = require('discord.js')
const client = new discord.Client()
client.login(require('./src/Configurations/Config.json').token)
client.triggers = new discord.Collection()
client.commands = new discord.Collection()
client.commandsUsed = 0 
require('./src/Util/Misc/EventLoadingHandler.js')(client)
const Enmap = require('enmap')
client.Prefix = new Enmap({name: 'prefix'})
client.Points = new Enmap({name: 'Points'})
client.Credits = new Enmap({name: 'credits'})
client.PP = new Enmap({name: 'PP'})
client.AutoMod = new Enmap({name: 'AutoMod'})
client.HowGay = new Enmap({name: 'HowGay'})